[project]
name = "langchain-rag"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "deepagents>=0.7.13",
    "dotenv>=0.9.9",
    "langchain>=1.4.0",
    "langchain-huggingface>=1.2.2",
    "langchain-openai>=1.6.2",
    "langchain-text-splitters>=1.1.2",
    "numpy>=2.5.3",
    "pypdf>=6.18.0",
    "requests>=2.34.2",
    "sentence-transformers>=6.0.1",
    "streamlit>=1.63.0",
    "torch>=2.14.0",
]
